Bottom tabs
AnoopManikanta/Flickr-Photo-Viewer pull request #1
Opened 2022-02-21 02:47 UTC by AnoopManikanta

- added bottom tab to navigate between 2 VCs search and favourites

2022-02-21 04:08 UTC, kunalgupta022 requested changes

2022-02-21 04:08 UTC, kunalgupta022 commented on AnoopExercises/Sources/AppDelegate.swift
> +//            let viewController = ViewController()
Please don't leave commented-out code. This may indicate either it was needed for some reason or removed as an afterthought. 
[Here's](https://kentcdodds.com/blog/please-dont-commit-commented-out-code) some additional reference material that you may want to look at.

2022-02-21 04:08 UTC, kunalgupta022 commented on AnoopExercises/Sources/SceneDelegate.swift
> +//        let viewController = ViewController()
Same as above.

2022-02-21 04:08 UTC, kunalgupta022 commented on AnoopExercises/Sources/UIWindowExtension.swift
> +        tabBarController.tabBar.tintColor = .systemPink
Are you sure the color is correct?
Is the color used in the figma designs equivalent to system pink?

2022-02-21 04:08 UTC, kunalgupta022 commented on Podfile
> +  # pod 'Sedwig', :git => 'git@github.com:surya-soft/Sedwig.git'
You can remove this for now. We can add it back when we come to RxSwift exercises.

2022-02-21 11:45 UTC, AnoopManikanta commented on AnoopExercises/Resources/Assets.xcassets/heart.imageset/Contents.json
> +      "filename" : "icons8-heart-50.png",
sure ill make the change

2022-02-21 11:45 UTC, AnoopManikanta commented on AnoopExercises/Resources/Assets.xcassets/search.imageset/Contents.json
> +      "filename" : "icons8-search-50.png",
sure ill make the change

2022-02-21 11:47 UTC, AnoopManikanta commented on AnoopExercises/Sources/AppDelegate.swift
> +//            let viewController = ViewController()
oh sorry, i forgot to remove it, ill take care from next time

2022-02-21 11:47 UTC, AnoopManikanta commented on AnoopExercises/Sources/SceneDelegate.swift
> +//        let viewController = ViewController()
sure ill remove it

2022-02-21 11:47 UTC, AnoopManikanta commented on AnoopExercises/Sources/UIWindowExtension.swift
> +        tabBarController.tabBar.tintColor = .systemPink
i used eyeDropper and changed the color to that in figma

2022-02-21 11:48 UTC, AnoopManikanta commented on Podfile
> +  # pod 'Sedwig', :git => 'git@github.com:surya-soft/Sedwig.git'
sure

2022-02-21 13:41 UTC, kunalgupta022 requested changes

2022-02-21 13:41 UTC, kunalgupta022 commented on AnoopExercises/Sources/UIWindowExtension.swift
> +        tabBarController.tabBar.tintColor = UIColor(named: "tintPink")
Please use R.color.tintPink to set color

2022-02-22 07:39 UTC, AnoopManikanta commented on AnoopExercises/Sources/UIWindowExtension.swift
> +        tabBarController.tabBar.tintColor = UIColor(named: "tintPink")
sure

2022-02-22 08:11 UTC, kunalgupta022 approved these changes

2022-02-22 08:13 UTC, kunalgupta022 approved these changes

2022-02-22 08:17 UTC, kunalgupta022 commented on AnoopExercises/Resources/Assets.xcassets/heart.imageset/Contents.json
> +      "filename" : "icons8-heart-50.png",
still not resolved

2022-02-22 08:17 UTC, kunalgupta022 commented on AnoopExercises/Resources/Assets.xcassets/search.imageset/Contents.json
> +      "filename" : "icons8-search-50.png",
still not resolved

2022-02-24 04:49 UTC, SahilDhawan requested changes

2022-02-24 04:49 UTC, SahilDhawan commented on AnoopExercises/Resources/Assets.xcassets/search.imageset/Contents.json
> +}
Why do we require a search icon? This is something that UIKit provides out of the box.

2022-02-24 04:49 UTC, SahilDhawan commented on AnoopExercises/Sources/FavouritesVC.swift
> +        navigationItem.title = "Favourites"
strings should come from Localizable.strings and we use should R.string in the view to access the hardcoded string.

2022-02-24 04:49 UTC, SahilDhawan commented on AnoopExercises/Sources/SearchVC.swift
> +        navigationItem.title = "Flickr"
Please use R.string to access hardcoded strings.

2022-02-24 04:49 UTC, SahilDhawan commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            embedInNavController(FavouritesVC(), title: "Favourites")
same feedback as above. Also, if we are passing in the title here, why do we need to use hardcoded string in `viewDidLoad` function of the viewController. cc @kunalgupta022

2022-02-24 04:49 UTC, SahilDhawan commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            items[x].image = UIImage(named: images[x])
highly recommend using R.image to access images. We should avoid hardcoded strings as much as we can and try using strongly typed resources (that is the reason why R.swift is included as a pod in the project). The reason here being that developers can easily make mistakes in hardcoded strings and this is not something that we can test at compile time.

2022-02-24 04:49 UTC, SahilDhawan commented on Dangerfile
> +warn("Big PR") if git.lines_of_code > 500
we can remove the Dangerfile since we don't have CI/CD enabled for this project. cc @kunalgupta022

2022-02-24 04:49 UTC, SahilDhawan commented on Gemfile
> +gem "danger-swiftformat"
everything apart from `cocoapods` should be removed here. Since we are not using Danger here, these dependencies are not required.

2022-02-24 04:49 UTC, SahilDhawan commented on README.md
> +### Danger
please remove Danger from README.md since we don't require it for this project.

2022-02-24 06:28 UTC, AnoopManikanta commented on AnoopExercises/Resources/Assets.xcassets/search.imageset/Contents.json
> +}
ill check that out

2022-02-24 06:28 UTC, AnoopManikanta commented on AnoopExercises/Sources/FavouritesVC.swift
> +        navigationItem.title = "Favourites"
yes ill make that change

2022-02-24 06:28 UTC, AnoopManikanta commented on AnoopExercises/Sources/SearchVC.swift
> +        navigationItem.title = "Flickr"
sure

2022-02-24 06:30 UTC, AnoopManikanta commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            embedInNavController(FavouritesVC(), title: "Favourites")
actually this title is for the tab bar controller for specific tabs

2022-02-24 06:33 UTC, AnoopManikanta commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            items[x].image = UIImage(named: images[x])
sure ill make the change

2022-02-24 06:34 UTC, AnoopManikanta commented on Dangerfile
> +warn("Big PR") if git.lines_of_code > 500
okay

2022-02-24 06:35 UTC, AnoopManikanta commented on Gemfile
> +gem "danger-swiftformat"
okay

2022-02-24 06:35 UTC, AnoopManikanta commented on README.md
> +### Danger
sure

2022-02-24 11:11 UTC, AnoopManikanta commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            embedInNavController(FavouritesVC(), title: "Favourites")
what i mean to say is if, i assign title for viewController tabBar automatically takes that name, and the title assigned in viewDidLoad is specifically for navigationItem, in the further PRs i have replaced it with Flickr image.

2022-02-24 11:38 UTC, kunalgupta022 requested changes

2022-02-24 11:38 UTC, kunalgupta022 commented on AnoopExercises/Sources/FavouritesVC.swift
> +class FavouritesVC: UIViewController {
```suggestion
class FavoritesVC: UIViewController {
```

2022-02-24 11:38 UTC, kunalgupta022 commented on AnoopExercises/Strings/Localizable.strings
> +favouritesTitle = "Favourites";
```suggestion
favoritesTitle = "Favorites";
```
Ensure User facing strings are spelled correctly for better user experience.

2022-02-24 11:38 UTC, kunalgupta022 commented on AnoopExercises/Sources/UIWindowExtension.swift
> +            embedInNavController(FavouritesVC(), title: "Favourites")
We still must ensure that there are no hard-coded strings in code ad this is error-prone.

2022-02-24 11:51 UTC, AnoopManikanta commented on AnoopExercises/Sources/FavouritesVC.swift
> +class FavouritesVC: UIViewController {
ill make the change

2022-02-24 11:51 UTC, AnoopManikanta commented on AnoopExercises/Strings/Localizable.strings
> +favouritesTitle = "Favourites";
ill make the change

2022-02-24 12:08 UTC, kunalgupta022 commented on AnoopExercises/Sources/FavoritesVC.swift
> +//  FavouritesVC.swift
Typo
```suggestion
//  FavoritesVC.swift
```

2022-02-24 12:09 UTC, AnoopManikanta commented on AnoopExercises/Sources/FavoritesVC.swift
> +//  FavouritesVC.swift
fixed it, sorry

2022-02-24 12:12 UTC, kunalgupta022 approved these changes

2022-02-28 05:57 UTC, SahilDhawan commented on AnoopExercises/Resources/Assets.xcassets/search.imageset/Contents.json
> +}
Not resolved?

2022-02-28 06:00 UTC, SahilDhawan approved these changes

2022-02-28 06:21 UTC, merged